Traceback (most recent call last):
  File "/Users/gianmaria/Desktop/LOOMTechnologies/ai_assistant/simple_ai.py", line 5, in <module>
    from fastapi import FastAPI, HTTPException
ModuleNotFoundError: No module named 'fastapi'
